### ISSUE TITLE
Ressource Pack

### ISSUE THREAD

**Issue by MagnasiePro** [Ekinoxx0/LoupGarou#1]
Le ressource pack ne se télécharge pas et kick le client.
Marche pourtant correctement sur la version de Leomelki.

**Comment by Ekinoxx0** [comment]
Bug lié au faite que le projet github du resourcepack semble indisponible,

Voir :
https://github.com/Ekinoxx0/LoupGarou/blob/master/src/main/java/dev/loupgarou/commands/subcommands/debug/ResourcePackCmd.java

Le lien finissant par /raw/ n'a pas l'air de fonctionner, peut-être github qui a changé sa méthode de download des fichiers brut
